Repository thomazllr/bibliotech, pull requests merged in 2025-05, with the labels that each got.

#15 feature: Adiciona manipulação de mensagem de sucesso e aprimora estilo nos formulários de usuário
  public/css/page/form-usuario.css
  public/js/pages/auth.js
  view/cadastro-usuario.html
  view/login.html
Labels: enhancement

#14 ✨ Feature: Adiciona filtro por faixa de preço na pesquisa de livros
  public/css/components.css
  public/js/pages/search-books.js
Labels: enhancement

#24 ✨ Feature: adiciona e aprimora página de detalhes do livro, além de correções visuais e funcionais
  dao/LivroDAO.php
  public/css/components.css
  public/css/page/detalhes.css
  public/js/pages/detalhes.js
  public/js/pages/genero.js
  public/js/pages/home.js
  public/js/pages/search-books.js
  public/js/utils/renderBooks.js
  view/detalhes-livro.html
Labels: enhancement

#32 ⚙Fix/resolvendo bugs
  README.md
  api/cadastro-usuario.php
  public/js/api/auth.js
  public/js/pages/auth.js
  public/js/pages/carrinho.js
  public/js/pages/livro.js
  relatorios/iteracao-3.md
  view/cadastro-usuario.html
  view/login.html
Labels: bug

#34 ✨ Feature: adicionar livro a lista de desejos do usuário
  api/lista-desejos.php
  dao/ListaDesejosDAO.php
  db/Database.php
  public/css/components.css
  public/css/page/detalhes.css
  public/js/api/lista-desejos.js
  public/js/pages/detalhes.js
  public/js/pages/home.js
  public/js/utils/modal-utils.js
  public/js/utils/renderBooks.js
Labels: enhancement

#33 Tabela de gerenciamento de editoras com suporte a criação/leitura/atualização e remoção de editoras.
  .cursorindexingignore
  .gitignore
  api/carrinho.php
  api/editora.php
  api/genero.php
  api/livro.php
  dao/CarrinhoDAO.php
  dao/EditoraDAO.php
  dao/GeneroDAO.php
  dao/LivroDAO.php
  dao/UsuarioDAO.php
  public/css/page/admin.css
  public/js/api/editora.js
  public/js/api/livro.js
  public/js/pages/detalhes.js
  public/js/pages/editora.js
  public/js/pages/livro.js
  public/js/status.js
  public/js/utils/toast.js
  view/admin.html
  view/cadastrar-livros.html
  view/carrinho.html
Labels: enhancement

#36 🛠️ Refactor: remover variável userId não utilizada e simplificar a obten…
  public/js/pages/carrinho.js
  public/js/pages/home.js
  public/js/pages/search-books.js
  public/js/utils/auth-utils.js
Labels: bug, refactor

#44 ✨Feature: Tela de Perfil do Usuário
  controllers/UsuarioController.php
  models/Usuario.php
  public/css/components.css
  public/css/page/admin.css
  public/css/page/carrinho.css
  public/css/page/detalhes.css
  public/css/page/form-usuario.css
  public/css/page/perfil.css
  public/js/api/usuario.js
  public/js/pages/auth.js
  public/js/pages/carrinho.js
  public/js/pages/detalhes.js
  public/js/pages/livro.js
  public/js/pages/perfil/dados-pessoais/data-service.js
  public/js/pages/perfil/dados-pessoais/form-handler.js
  public/js/pages/perfil/dados-pessoais/index.js
  public/js/pages/perfil/dados-pessoais/utils.js
  public/js/pages/perfil/main.js
  public/js/pages/perfil/shared/menu-toggle.js
  public/js/utils/renderBooks.js
  repositories/UsuarioRepository.php
  view/admin.html
  view/cadastro-usuario.html
  view/carrinho.html
  view/detalhes-livro.html
  view/generos.html
  view/home.html
  view/login.html
  view/perfil.html
Labels: enhancement

#45 ✨ Feature: fluxo de checkout implementado com sucesso
  .htaccess
  controllers/PedidoController.php
  models/Pedido.php
  models/PedidoItem.php
  public/css/page/carrinho.css
  public/css/page/finalizacao.css
  public/index.php
  public/js/api/pedido.js
  public/js/pages/carrinho-view.js
  public/js/pages/pedido.js
  repositories/CarrinhoRepository.php
  repositories/PedidoItemRepository.php
  repositories/PedidoRepository.php
  view/carrinho.html
  view/finalizar.html
Labels: enhancement

#49 ✨Feature: Implementa página de exibição da lista de desejos
  public/js/pages/perfil/lista-desejo/desejos-service.js
  public/js/pages/perfil/lista-desejo/index.js
  public/js/pages/perfil/main.js
  view/perfil.html
Labels: enhancement
