Repository thomazllr/bibliotech, pull requests merged in 2025-04, with the labels that each got.

#1 ✨ Feature: Implementação da Tela Home & Conexão com banco de dados
  .gitignore
  .hintrc
  core/load_env.php
  db/Database.php
  db/db-config.php
  public/css/base.css
  public/css/components.css
  public/css/layout.css
  public/css/main.css
  public/css/page/admin.css
  public/css/page/home.css
  public/js/navigation.js
  relatorios/iteracao-1.md
  view/admin.html
  view/home.html
  view/teste.html
  view/teste.php
Labels: enhancement

#3 ✨ Feature(admin): adiciona tela de administração com verificação de acesso
  .hintrc
  api/auth.php
  public/css/components.css
  public/css/page/admin.css
  public/css/page/login.css
  public/js/admin.js
  public/js/auth-guard.js
  public/js/pages/auth.js
  public/js/status.js
  relatorios/iteracao-1.md
  view/admin.html
  view/home.html
Labels: enhancement

#4 ✨ Feature: implementação do modal de cadastro de livro
  .hintrc
  api/livro.php
  dao/LivroDAO.php
  public/css/page/admin.css
  public/css/page/cadastrar-livros.css
  public/js/admin.bundle.js
  public/js/admin.js
  public/js/api/auth.js
  public/js/api/livro.js
  public/js/config.js
  public/js/pages/livro.js
  public/js/status.js
  view/admin.html
  view/cadastrar-livros.html
Labels: enhancement

#5 ✨ Feature: Implementação de busca e filtragem de livros/gêneros e melhorias na UI do catálogo de livros.
  api/livro.php
  dao/LivroDAO.php
  public/css/base.css
  public/css/components.css
  public/js/api/livro.js
  public/js/config.js
  public/js/pages/home.js
  public/js/pages/search-books.js
  relatorios/iteracao-1.md
  view/admin.html
  view/home.html
  view/login.html
Labels: enhancement

#6 ✨ Feature: Implementa método DELETE para exclusão de livros no front e back-end
  api/livro.php
  dao/LivroDAO.php
  public/js/api/livro.js
  public/js/pages/livro.js
  relatorios/iteracao-1.md
Labels: enhancement

#7 ✨ Feature: Implementa método PUT para atualização de livros existentes no front e back-end
  api/livro.php
  dao/LivroDAO.php
  public/js/api/livro.js
  relatorios/iteracao-1.md
Labels: documentation, enhancement

#8 ✨ Feature: Implementa tabela funcional de ADMIN com métodos CRUD
  api/livro.php
  dao/LivroDAO.php
  public/css/components.css
  public/css/page/admin.css
  public/js/api/livro.js
  public/js/pages/livro.js
  view/admin.html
Labels: enhancement

#9 📢 Release v1.0
  .gitignore
  .hintrc
  README.md
  api/auth.php
  api/livro.php
  core/load_env.php
  dao/LivroDAO.php
  dao/UsuarioDAO.php
  db/Database.php
  db/db-config.php
  prototipos/administrador.png
  prototipos/biblioteca.png
  prototipos/cadastro.png
  prototipos/carrinho.png
  prototipos/detalhes.png
  prototipos/finalizada.png
  prototipos/home.png
  prototipos/leitor.png
  prototipos/login.png
  prototipos/perfil.png
  public/css/base.css
  public/css/components.css
  public/css/layout.css
  public/css/main.css
  public/css/page/admin.css
  public/css/page/cadastrar-livros.css
  public/css/page/home.css
  public/css/page/login.css
  public/js/admin.bundle.js
  public/js/api/auth.js
  public/js/api/livro.js
  public/js/auth-guard.js
  public/js/config.js
  public/js/modal.js
  public/js/navigation.js
  public/js/pages/auth.js
  public/js/pages/home.js
  public/js/pages/livro.js
  public/js/pages/search-books.js
  public/js/profile-menu.js
  public/js/status.js
  relatorios/iteracao-1.md
  relatorios/iteracao-2.md
  view/admin.html
  view/cadastrar-livros.html
  view/home.html
  view/login.html
  view/teste.html
  view/teste.php
Labels: release

#10 ✨ Feature: Integração da Tabela Gênero
  api/genero.php
  api/livro.php
  dao/GeneroDAO.php
  dao/LivroDAO.php
  public/css/components.css
  public/js/api/genero.js
  public/js/api/livro.js
  public/js/pages/genero.js
  public/js/pages/home.js
  public/js/pages/livro.js
  public/js/pages/search-books.js
  public/js/utils/renderBooks.js
  view/admin.html
  view/home.html
Labels: enhancement

#11 ✨ Feature: Permite inserção de imagem via URL
  .hintrc
  api/livro.php
  dao/LivroDAO.php
  dao/UsuarioDAO.php
  public/js/api/livro.js
  public/js/auth-guard.js
  public/js/pages/auth.js
  public/js/pages/home.js
  public/js/pages/livro.js
  public/js/pages/search-books.js
  public/js/status.js
  public/js/utils/renderBooks.js
  view/admin.html
  view/teste.html
  view/teste.php
Labels: enhancement
